from __future__ import annotations

from pathlib import Path
import streamlit as st

ROOT = Path(__file__).resolve().parents[2]
FIXTURES = ROOT / "fixtures" / "incidents"
MAX_FILE_SIZE = 200 * 1024 * 1024

def _load_demo(filename: str):
    file = FIXTURES / filename

    if file.exists():
        st.session_state["incident_text"] = file.read_text(encoding="utf-8")


def header():
    st.title("🛡 Guardian Autopilot")
    st.caption("AI-Powered Multi-Agent Incident Response Platform")
    st.markdown(""" Built with **Alibaba Cloud Qwen** • An Open Source Project by **Gotihub** """)

    c1, c2, c3 = st.columns(3)
    with c1:
        st.success("⚡ FastAPI")

    with c2:
        st.info("🤖 Alibaba Cloud Qwen")

    with c3:
        st.warning("🖥 Streamlit")

    st.info(
        """
🚀 **Try it in under 30 seconds**
• Upload your own incident

• Paste incident text

• Or use one of the built-in demo incidents below.
"""
    )

    st.divider()


def uploader():

    st.subheader("📂 Incident Source")

    uploaded = st.file_uploader(
        "Upload Incident File",
        type=["txt"],
        help="TXT files only • Maximum size 200 MB",
    )
    
    if uploaded is not None and uploaded.size > MAX_FILE_SIZE:
        st.error("File exceeds the maximum allowed size of 200 MB.")
        st.stop()

    st.markdown("### OR")

    if "incident_text" not in st.session_state:
        st.session_state["incident_text"] = ""

    st.markdown("### 🚀 Demo Incidents")

    c1, c2, c3, c4 = st.columns(4)
    with c1:
        if st.button("🟢 Low", use_container_width=True):
            _load_demo("low_incident.txt")

    with c2:
        if st.button("🟡 Medium", use_container_width=True):
            _load_demo("medium_incident.txt")

    with c3:
        if st.button("🔴 Critical",use_container_width=True):
            _load_demo("mixed_incident.txt")

    with c4:
        sample = FIXTURES / "mixed_incident.txt"

        if sample.exists():
            st.download_button(
                "⬇ Sample",
                data=sample.read_text(
                    encoding="utf-8"
                ),
                file_name="guardian_sample_incident.txt",
                mime="text/plain",
                use_container_width=True,
            )

    st.markdown("### OR")

    text = st.text_area(
        "Paste Incident",
        key="incident_text",
        height=220,
        placeholder="""Example

AWS_ACCESS_KEY_ID=AKIAxxxxxxxxxxxxxxxx

AWS_SECRET_ACCESS_KEY=xxxxxxxxxxxxxxxx

ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

xoxb-xxxxxxxxxxxxxxxxxxxxxxxxxxxx

Paste logs, leaked credentials, emails or any security incident here...
""",
    )

    st.markdown("")

    scan = st.button(
        "🛡 Start Investigation",
        type="primary",
        use_container_width=True,
    )

    return uploaded, text, scan


def metrics(result):

    st.divider()

    st.subheader("📊 Investigation Summary")

    c1, c2, c3 = st.columns(3)

    with c1:
        st.metric("🚨 Risk",result["risk"])

    with c2:
        st.metric("🤖 Decision",result["decision"])

    with c3:
        st.metric("✅ Workflow",result["state"])


def report(report):

    st.divider()

    st.subheader("📑 Executive Incident Report")

    st.caption("Generated by Guardian Autopilot using Alibaba Cloud Qwen")

    st.code(report["content"],language="text")

    st.download_button(
        "⬇ Download Executive Report",
        data=report["content"],
        file_name="guardian_report.txt",
        mime="text/plain",
        use_container_width=True,
    )


def footer():
    st.divider()
    st.markdown(
        """
<div style="
    text-align:center;
    padding:18px;
    color:#6b7280;
    font-size:14px;
    line-height:1.8;
">

<b>🛡 Guardian Autopilot v1.0.1</b><br>

AI-Powered Multi-Agent Incident Response Platform<br><br>

Powered by <b>Alibaba Cloud Qwen</b><br>

Deployed on <b>Alibaba Cloud ECS</b><br>

Open Source by <b>Gotihub</b><br><br>

© 2026 Gotihub

</div>
""",
        unsafe_allow_html=True,
    )